version: "3"

services:
  # Nessie Catalog Server Using In-Memory Store
  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_HTTP_PORT=19120
      - nessie.version.store.type=ROCKSDB
    volumes:
      - ./nessie:/tmp/nessie-rocksdb-store  # Mount local directory to persist RocksDB data
    ports:
      - 19120:19120  # Expose Nessie API port
    networks:
      iceberg-network:
  # Minio Storage Server
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    networks:
      iceberg-network:
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - ./minio/data:/data
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address ':9001' &
      sleep 5;
      mc alias set myminio http://localhost:9000 admin password;
      mc mb myminio/datalakehouse;
      tail -f /dev/null"
  # Dremio
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
    container_name: dremio
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    networks:
      iceberg-network:
    volumes:
      - ./dremio/data:/opt/dremio/data
      - ./dremio/lib:/var/lib/dremio
      - ./dremio/local:/localFiles
networks:
  iceberg-network:
